# Generated by Django 5.0.4 on 2024-10-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
